--ALTER TABLE

SELECT * 
	INTO TTEMP
	FROM ALUNOS;

EXEC SP_COLUMNS TTEMP

--ADICIONAR UMA COLUNA
ALTER TABLE TTEMP
	ADD CPF NUMERIC(11);

UPDATE TTEMP
	SET CPF = 11122233344, EMAIL = 'MARIA@JOAQUINA.COM.BR'
	WHERE ID_ALUNO = 3;

SELECT * FROM TTEMP;

ALTER TABLE TTEMP
	ADD EMAIL VARCHAR(100);

--ALTERAR TIPO DE DADOS DE UMA COLUNA
ALTER TABLE TTEMP
	ALTER COLUMN CPF VARCHAR(15)

EXEC SP_COLUMNS  TTEMP