--IF...ELSE...

--------------------------------------
DROP TABLE TTEMP

SELECT *
	INTO TTEMP
	FROM ALUNOS;

IF 10 > 20
	SELECT '10 É MAIOR QUE 20';
ELSE IF 10 < 20
	SELECT '10 É MENOR QUE 20';
ELSE
	SELECT '10 É IGUAL A 20';

IF DATENAME(WEEKDAY, GETDATE()) IN ('Saturday', 'Sunday')
	SELECT 'Estamos no fim de semana, Hoje é ' + DATENAME(WEEKDAY, GETDATE());
ELSE
	SELECT 'Estamos em um dia de semana, Hoje é ' + DATENAME(WEEKDAY, GETDATE());


DECLARE @vIdadeMax INT;
DECLARE @vParam INT;
	SET @VIdadeMax = 30;
	SET @vParam = 25;

IF @vIdadeMax >= @vParam
	SELECT NOME, DATA_NASCIMENTO, DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) IDADE
		FROM TTEMP
		WHERE DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) < @vIdadeMax
	ORDER BY 3 ASC;
ELSE
	SELECT NOME, DATA_NASCIMENTO, DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) IDADE
		FROM TTEMP
		WHERE DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) < @vIdadeMax
	ORDER BY 3 ASC;

DROP TABLE TTEMP