--TRIGGERS
----------------

CREATE TABLE tbSaldos
(
	PRODUTO VARCHAR(10),
	SALDO_INICIAL NUMERIC(10),
	SALDO_FINAL NUMERIC(10),
	DATA_ULT_MOV DATETIME
);
GO

INSERT INTO tbSaldos
(PRODUTO, SALDO_INICIAL, SALDO_FINAL, DATA_ULT_MOV)
VALUES
('Produto A', 0, 100, GETDATE())
GO

CREATE TABLE tbVendas
(
	ID_VENDAS INT,
	PRODUTO VARCHAR(10),
	QUANTIDADE INT,
	DATA DATETIME
);
GO

CREATE SEQUENCE SEQ_TBVENDAS
	AS INT
	START WITH 1
	INCREMENT BY 1;

CREATE TABLE TBHISTORICOVENDAS
(
	PRODUTO VARCHAR(10),
	QUANTIDADE INT,
	DATA_VENDA DATETIME
);
GO

-------------- criando a trigger

CREATE TRIGGER TRG_AJUSTA_SALDO
ON TBVENDAS  -- CASO ESSA TABELA SEJA DELETADA, A TRIGGER TAMBEM É AUTOMATICAMENTE DELETADA.
FOR INSERT -- EXISTEM OUTROS TIPOS DE TRIGGERS, PODE SER USADAS EM INSERTS, UPDATES, DELETES, OU O QUE FOR NESCESSARIO -- PESQUISAR SOBRE --
AS
BEGIN
	DECLARE @QUANTIDADE INT;
	DECLARE @DATA       DATETIME;
	DECLARE @PRODUTO    VARCHAR(10);

	SELECT @DATA = DATA, @QUANTIDADE = QUANTIDADE, @PRODUTO = PRODUTO FROM inserted
	
	UPDATE TBSALDOS	
		SET SALDO_FINAL = SALDO_FINAL - @QUANTIDADE,
			DATA_ULT_MOV = @DATA
		WHERE PRODUTO = @PRODUTO;

	INSERT INTO TBHISTORICOVENDAS
	(PRODUTO, QUANTIDADE, DATA_VENDA)
		VALUES
		(
			@PRODUTO,
			@QUANTIDADE,
			@DATA
		)
END
GO

INSERT INTO TBVENDAS
(ID_VENDAS, PRODUTO, QUANTIDADE, DATA)
VALUES
(
	NEXT VALUE FOR SEQ_TBVENDAS, 'Produto A', 6, GETDATE()
);

SELECT * FROM tbVendas;
SELECT * FROM tbSaldos;
SELECT * FROM TBHISTORICOVENDAS;