--FUNÇOES DE DATAS NO SQL SERVER

--TIPOS DE DATA E HORA
	
	--DATETIME - ARMAZENA ATÉ CENTESIMOS DE SEGUNDOS
	--SMALLDATETIME - ARMAZENA ATÉ SEGUNDOS

--FUNÇÕES: GETDATE, DATEPART, DATEADD, DETEDIFF

--GETDATE()
SELECT GETDATE(); -- CAPTURA A DATA ATUAL

--METODOS DE CONVERSÃO DE DATAS
SELECT CONVERT(CHAR, GETDATE(), 103); -- FORMATO DD/MM/YYYY
SELECT CONVERT(CHAR, GETDATE(), 102); -- FORMATO YYYY/MM/DD
SELECT CONVERT(CHAR, GETDATE(), 3); -- TABELA ANSI SLQ

-- FILTRO DE DATA  POR DIA, MES OU ANO
SELECT DAY(GETDATE()) AS DIA;
SELECT MONTH(GETDATE()) AS MÊS;
SELECT YEAR(GETDATE()) AS ANO;
SELECT YEAR('11/11/1920') AS "YEAR";


--DATEPART -- REALIZA UM FILTRO COMO OS DOS COMANDOS ACIMA
SELECT DATEPART(DAY, GETDATE()) AS DIA;
SELECT DATEPART(MONTH, GETDATE()) AS MES;
SELECT DATEPART(YEAR, GETDATE()) AS ANO;

--DATEADD

SELECT DATEADD(YEAR, -2, GETDATE()) AS "Data"; -- subtrai dois anos da data atual (DD/MM/YYYY HORAS, MINUTOS, SEGUNDOS) 
SELECT DATEADD(DAY, 25, GETDATE()) AS "DATA";

-- CONVERÇÃO DE DATAS COM CONVERT 
SELECT CONVERT(DATE, DATEADD(MONTH, -5, GETDATE())); 
SELECT CONVERT(DATETIME, DATEADD(HOUR, 3, GETDATE()));
SELECT CONVERT(SMALLDATETIME, DATEADD(HOUR, -5, GETDATE()));


--DATEDIFF
SELECT DATEDIFF(YEAR, GETDATE(), DATEADD(YEAR, 4, GETDATE())) AS ANOS;
SELECT DATEDIFF(MONTH, GETDATE(), DATEADD(YEAR, 4, GETDATE())) AS MESES;
SELECT DATEDIFF(DAY, GETDATE(), DATEADD(YEAR, 4, GETDATE())) AS DIAS;
SELECT DATEDIFF(HOUR, GETDATE(),DATEADD(YEAR, 4, GETDATE())) AS HORAS;

SELECT DATEDIFF(SECOND, '10/10/2002', GETDATE()) AS "Segundos de vida"

SELECT DATEDIFF(YEAR, '10/10/2002', GETDATE()) AS "Anos de vida"