--UPDATE

SELECT *
	INTO TBTEMP
	FROM ALUNOS;

SELECT * FROM TBTEMP;

DROP TABLE TBTEMP;
--UPDATE PADRAO

UPDATE TBTEMP
	SET SEXO = NULL -- ALTERA TODAS LINHAS DA TABELA POIS NAO FOI INCLUIDO O 'WHERE';

UPDATE TBTEMP
	SET SEXO = 'M'
	WHERE nome like 'Gustavo%' or nome like 'Cezar%' or nome like 'Nicolas%' or nome like 'Al%'; 

UPDATE TBTEMP
	SET SEXO = 'F'
	WHERE SEXO IS NULL;


--SETANDO SEXO PARA NULL USANDO IN
UPDATE TBTEMP
	SET SEXO = NULL
	WHERE ID_ALUNO IN (1, 3, 5);

SELECT * FROM TBTEMP;